### ISSUE TITLE
debug50 not starting

### ISSUE THREAD

**Issue by MarcoAlvarez** [cs50/harvard.cs50.debug#30] opened 2018-09-12 22:44 UTC
Several students have reported this error, even when breakpoints are all set:
```
"Looks like you haven't set any breakpoints. Set at least one breakpoint by clicking to the left of a line number and then re-run debug50!"
```

I am not sure if this is the right place for a fix, but it appears that the regular expression below (from line 55 on file `harvard.cs50.debug/bin/debug50`) may be the cause of the problem:
```
sources=$(echo "$sources" | grep -Eo "/.*\.c(pp)?,?")
```

**Comment by kzidane** [comment] 2018-09-12 22:49
@MarcoAlvarez are you trying to debug C programs or C++ ones? Single or multi source files? Are you sure you're in the right folder and setting breakpoints in the right file? Have you tried removing the breakpoints and re-adding them?

**Comment by kzidane** [comment] 2018-09-12 22:52
Also have your compiled your program with `-ggdb3`?

**Comment by MarcoAlvarez** [comment] 2018-09-12 22:57
I tested on `.c .cpp .cc` files.  `debug50` only works with `.c` files, it shows that error on all other extensions.

The line I copied above appears to have a mistake in the regular expression `"/.*\.c(pp)?,?"`.  The first character `'/'` may not be necessary.  If no filenames are matched the variable `breakpoint` will remain false and line 78 will trigger the error message.

**Comment by kzidane** [comment] 2018-09-12 23:00
How did you compile your cpp program?

**Comment by MarcoAlvarez** [comment] 2018-09-12 23:04
`g++ -g test.cpp -o test`

**Comment by MarcoAlvarez** [comment] 2018-09-12 23:06
The same error has been reported by a good number of students  (fresh install and before/after running `update50`).

**Comment by kzidane** [comment] 2018-09-12 23:12
I'm afraid I can't replicate on my end. Could you please share the workspace with username "kzidane"? Share button should be on the top-right corner of the IDE. Please close any tabs that are open for your workspace after sharing. Afraid the debugger supports only one client now.

**Comment by kzidane** [comment] 2018-09-12 23:13
Also, what's the path of the program that you're trying to debug in this workspace?

**Comment by MarcoAlvarez** [comment] 2018-09-12 23:17
I am using CS50IDE offline  (couldn't find the share button)

+ path: `/home/ubuntu/workspace/main.cpp`
+ compile: `g++ -g main.cpp -o test`
+ set 1 or 2 breakpoints
+ debug: `debug50 test`

+ error message:
`Looks like you haven't set any breakpoints. Set at least one breakpoint by clicking to the left of a line number and then re-run debug50!`

**Comment by kzidane** [comment] 2018-09-13 00:29
Okay I think I see where the issue is. Does this command output anything if you run it in your offlien workspace?

```
$ diff `which debug50` <(curl -s https://raw.githubusercontent.com/cs50/harvard.cs50.debug/master/bin/debug50)
```

**Comment by MarcoAlvarez** [comment] 2018-09-13 12:38
here is the output of the `diff` command:
```
<     sources=$(echo "$sources" | grep -Eo "/.*\.c,?")
---
>     sources=$(echo "$sources" | grep -Eo "/.*\.c(pp)?,?")
```

**Comment by MarcoAlvarez** [comment] 2018-09-13 14:45
Thanks for the quick fix.  It works great with `.c` and `.cpp` files.  However, I still see the same error with the `.cc` extension.  For source files with such extension the regex will need to be changed.  Thanks again.

**Comment by kzidane** [comment] 2019-10-11 21:16
This should be fixed.

**Closed by kzidane** 2019-10-11 21:16 UTC

**Comment by shantanu79** [comment] 2021-02-02 14:41
I can't use debug50 on online cs50 ide

**Comment by kzidane** [comment] 2021-02-02 15:09
@shantanu79 you need to be more specific.
